export const MOCK_SERVICES = [
  {
    id: "1",
    name: "Hair Cutting & Styling",
    description: "Professional haircuts and styling tailored to your face shape and personal preference.",
    price: "₹300+",
    category: "Hair",
    imageUrl: "https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=2674&auto=format&fit=crop",
    benefits: ["Customized Style", "Expert Advice", "Premium Finish"],
  },
  {
    id: "2",
    name: "Hair Spa",
    description: "Deep conditioning and nourishing hair spa treatments to revive dull and damaged hair.",
    price: "₹800+",
    category: "Hair",
    imageUrl: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=2670&auto=format&fit=crop",
    benefits: ["Deep Nourishment", "Scalp Health", "Relaxation"],
  },
  {
    id: "3",
    name: "Hair Coloring",
    description: "From subtle highlights to bold transformations using premium color products.",
    price: "₹1500+",
    category: "Hair",
    imageUrl: "https://images.unsplash.com/photo-1600948836101-f9ffda59d250?q=80&w=2536&auto=format&fit=crop",
    benefits: ["Long-lasting Color", "Vibrant Shine", "Damage Protection"],
  },
  {
    id: "4",
    name: "Bridal Makeup",
    description: "Elegant and flawless bridal makeup to make your special day truly memorable.",
    price: "₹8000+",
    category: "Bridal",
    imageUrl: "https://th.bing.com/th/id/OIP.61rIbEzGgs5Xi-H3G42ciwHaLH?w=118&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3",
    benefits: ["HD Finish", "Long-lasting Wear", "Premium Products"],
  },
  {
    id: "5",
    name: "Facial & Skin Care",
    description: "Rejuvenating facials and skin treatments tailored to your unique skin type.",
    price: "₹1000+",
    category: "Skin",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=2669&auto=format&fit=crop",
    benefits: ["Deep Cleansing", "Glowing Skin", "Anti-aging"],
  },
  {
    id: "6",
    name: "Beard Grooming",
    description: "Precision beard shaping, trimming, and grooming for the modern gentleman.",
    price: "₹200+",
    category: "Hair",
    imageUrl: "https://th.bing.com/th/id/OIP.W9M3ogyjuhyijr9kFH8xhgHaEo?w=295&h=184&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3",
    benefits: ["Sharp Edges", "Beard Softening", "Professional Look"],
  },
  {
    id: "7",
    name: "Keratin Treatment",
    description: "Frizz-free, smooth, and manageable hair with our luxury keratin treatments.",
    price: "₹4000+",
    category: "Hair",
    imageUrl: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=2670&auto=format&fit=crop",
    benefits: ["Frizz Control", "Intense Smoothness", "Long-lasting"],
  },
  {
    id: "8",
    name: "Smoothening & Rebonding",
    description: "Permanent hair straightening solutions for sleek and straight hair.",
    price: "₹4500+",
    category: "Hair",
    imageUrl: "https://images.unsplash.com/photo-1501699169021-3759ee435d66?q=80&w=2574&auto=format&fit=crop",
    benefits: ["Permanent Straightness", "Sleek Look", "Manageability"],
  },
  {
    id: "9",
    name: "Kids Haircut",
    description: "Gentle and stylish haircuts for children in a friendly environment.",
    price: "₹200+",
    category: "Hair",
    imageUrl: "https://images.unsplash.com/photo-1620000617482-821324eb9a14?q=80&w=2670&auto=format&fit=crop",
    benefits: ["Friendly Staff", "Safe Environment", "Cute Styles"],
  },
  {
    id: "10",
    name: "Party Makeup",
    description: "Glamorous makeup looks for parties, events, and special occasions.",
    price: "₹2500+",
    category: "Bridal",
    imageUrl: "https://th.bing.com/th?q=Beauty+Parlour+Party+Makeup&w=120&h=120&c=1&rs=1&qlt=70&r=0&o=7&cb=1&dpr=1.5&pid=InlineBlock&rm=3&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1&mw=247",
    benefits: ["Event Ready", "Flawless Base", "Eye Catching"],
  }
];
